--> selectAll
SELECT * FROM PRODUCT_CODE;
--> select
SELECT * FROM PRODUCT_CODE WHERE PROD_CODE = ?
OR DESCRIPTION = ?;
--> insertRecord
INSERT INTO PRODUCT_CODE
(PROD_CODE, DISCOUNT_CODE, DESCRIPTION)
VALUES (?, ?, ?);
--> updateRecord
UPDATE PRODUCT_CODE SET PROD_CODE = ?,
DISCOUNT_CODE = ?
WHERE DESCRIPTION = ?;